// <auto-generated />
using System;
using DeliverIT.Pagamento.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DeliverIT.Pagamento.Infrastructure.Migrations
{
    [DbContext(typeof(PagamentoDbContext))]
    [Migration("20251115091645_InitialCreatePostgres")]
    partial class InitialCreatePostgres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DeliverIT.Pagamento.Domain.Entities.ContaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DiasEmAtraso")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegraAplicada")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorCorrigido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ContasPagar");
                });
#pragma warning restore 612, 618
        }
    }
}
